Fix exception handling syntax when container creation fails
When container creation fails, the error I get is:

Traceback (most recent call last):
  File "/home/ubuntu/lxd_tools/create-pylxd", line 41, in <module>
    print(('Failed to create profile: %s') % data.get('metadata'))

This prevents the user from seeing the exception text from container_init().
Since data is only defined in the 'try:' above, I simply removed the reference.

After this change, I hit a different syntax-related issue:

Traceback (most recent call last):
  File "/home/ubuntu/lxd_tools/create-pylxd", line 43, in <module>
    raise Exception(msg.format(e), instance_id=name)
TypeError: exceptions.Exception does not take keyword arguments

I simply dropped the keyword to get past this. Now I see:

Traceback (most recent call last):
  File "/home/ubuntu/lxd_tools/create-pylxd", line 42, in <module>
    raise Exception(msg.format(e), name)
Exception: ('Cannot create container: [Errno 111] Connection refused', 'test1')

Ah! Now I see the problem. lxd isn't running :)